In [197]:
from forward_backward_AD import *

import numpy as np
import torch
import time, timeit

import scipy.io

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [192]:
workspace = scipy.io.loadmat(r'../Data Sets/Debug Data/workspace_calc_grad.mat')

c:\Users\Bruker\anaconda3\envs\SAXSTT\lib\site-packages\scipy\io\matlab\mio.py:226: MatReadWarning: Duplicate variable name "None" in stream - replacing previous with new
Consider mio5.varmats_from_mat to split file into single variable files
  matfile_dict = MR.get_variables(variable_names)


In [3]:
print(workspace.keys())

dict_keys(['__header__', '__version__', '__globals__', 'opt_inputs', 'p', 's', 'projection', 'E', 'numOfCoeffs', 'skip_optimization', 'None', 'return_synth_proj', 'return_Ereg', 'find_coefficients', 'find_orientation', 'find_grad', 'phi_det', 'theta_det', 'l', 'm', 'nx', 'ny', 'nz', 'numOfsegments', 'numOfvoxels', 'mask3D', 'numOfpixels', 'numOfordersopt', 'theta_struct', 'phi_struct', 'a', 'ii', 'grad_a', 'grad_theta_struct', 'grad_phi_struct', 'zeros_struct', 'Ylm_coef', 'a_temp', 'a_temp1', 'a_temp2', 'ones_struct', 'unit_q_beamline', 'N', 'x', 'y', 'z', 'X', 'Y', 'Z', '__function_workspace__'])


In [193]:
theta_struct_it = workspace['theta_struct']
phi_struct_it = workspace['phi_struct']
a_temp_it =    workspace['a_temp']
ny = workspace['ny']
nx = workspace['nx']
nz = workspace['nz']
numOfsegments = workspace['numOfsegments']
current_projection = workspace['projection'][0,0]#[2]
p = workspace['p']
X = workspace['X']
Y = workspace['Y']
Z = workspace['Z']
numOfpixels = workspace['numOfpixels']
unit_q_beamline = workspace['unit_q_beamline']
Ylm_coef = workspace['Ylm_coef']
find_coefficients = workspace['find_coefficients']
find_orientation = workspace['find_orientation']
numOfCoeffs = workspace['numOfCoeffs']
numOfvoxels = workspace['numOfvoxels']



In [188]:
#print(current_projection[0,0][2].shape)
# Testing shit

print(type(numOfvoxels))

yo = int(np.squeeze(numOfvoxels))

print(yo)

print(type(yo))

new_tens = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], dtype=torch.float64).reshape(4,4)
print(new_tens)


A = torch.rand((3,3,64))
B = torch.rand((3,8))
#C = torch.matmul(A[0], B) # Have to figure out how this works. 

projection_data = torch.tensor(
        current_projection["data"])

print(projection_data.shape)

print(current_projection["data"].shape)
print(current_projection["Rot_exp"].shape)


<class 'numpy.ndarray'>
64
<class 'int'>
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]], dtype=torch.float64)
torch.Size([4, 4, 8])
(4, 4, 8)
(3, 3)


Done debugging. Error is at least correct. 

In [198]:
main(theta_struct_it, phi_struct_it, a_temp_it, ny, nx, nz, numOfsegments, current_projection, p, X, Y, Z, numOfpixels, unit_q_beamline, Ylm_coef, find_coefficients, find_orientation, numOfCoeffs, numOfvoxels)

INFO:root:data_synt_vol is nan: False
INFO:root:proj_out_all is nan: False
INFO:root:permuted_data is nan: False
INFO:root:permuted data dtype: torch.float64
INFO:root:proj_out_all dtype: torch.float32
INFO:root:aux_diff_poisson is nan: False
INFO:root:aux_diff_poisson dtype: torch.float64
INFO:root:aux_diff_poisson shape: torch.Size([8, 4, 4])
INFO:root:tensor([[[-0.4607, -0.4491, -0.4222, -0.4283],
         [-0.5100, -0.9163, -0.8323, -0.5868],
         [-2.4404, -2.6914, -1.3356, -0.7975],
         [-4.3477, -4.0441, -2.9266, -1.4890]],

        [[-0.4492, -0.4776, -0.5748, -1.5065],
         [-0.4655, -0.9761, -2.6697, -2.8522],
         [-1.2614, -3.3904, -3.4696, -4.8108],
         [-2.3583, -3.0658, -5.6401, -5.2958]],

        [[-0.8568, -0.7009, -0.7631, -1.9899],
         [-0.7022, -0.7295, -2.0036, -3.9800],
         [-0.6603, -0.8244, -2.3033, -5.5066],
         [-0.6817, -0.7948, -3.0790, -5.0523]],

        [[-1.9263, -1.5291, -1.2819, -1.3334],
         [-1.8212, -1.4054

(0.20767428344614638,
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.14486932, -0.19772307, -0.25057683, -0.30343059,
        -0.16993861, -0.22433006, -0.2787215 , -0.33311295, -0.10750407,
        -0.10607128, -0.10463849, -0.10320571,  0.        ,  0.        ,
         0.        ,  0.        , -0.22354726, -0.32561551, -0.42768377,
        -0.52975202, -0.25339509, -0.35948617, -0.46557724, -0.57166832,
        -0.12877967, -0.12677392, -0.12476817, -0.12276241,  0.        ,
         0.        ,  0.        ,  0.        , -0.10882365, -0.16727035,
        -0.22571705, -0.28416376, -0.1184528 , -0.17900811, -0.23956343,
        -0.30011874, -0.04521855, -0.04348648, -0.04175441, -0.04002234,
         0.        ,  0.        ,  0.        ,  0.        ]),
 array([], dtype=float64),
 array([], dt

In [146]:
x = np.arange(64).reshape(4,4,4)
y = np.arange(64).reshape(4,4,4)

lower = np.argwhere( x>10)
upper = np.argwhere(x<20)

y = np.argwhere( (x>10) & (x<20) & (y>15) & (y<25) )
print(y)

# Next is out of bounds. Index 5 found when size is 4, index 3 is therefore max. 
print(x[y[:,0], y[:,1], y[:,2] ])

[[1 0 0]
 [1 0 1]
 [1 0 2]
 [1 0 3]]
[16 17 18 19]


In [168]:

# print(X)
# print('\n')
# print(Y)

Ax = np.floor(
    X - (-1.38545603) + 1
)  # Drop +1 due to 0-indexing. AI suggested, but believe I should copy cpp-code
Ay = np.floor(Y - (-0.19120833) + 1)

indices = np.argwhere( (Ax>0) & (Ax<4) & (Ay>0) & (Ay<4) )

print(Ax[indices[:,0], indices[:,1], indices[:,2] ])
print(Ay[indices[:,0], indices[:,1], indices[:,2] ])

[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.
 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [187]:
u1 = np.ones((3,3,3))
u2 = np.ones((3,3,3))

v = torch.tensor( u1 @ u2)
print(v)

tensor([[[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]], dtype=torch.float64)


In [201]:
# Check out nan values

permuted_data = np.load(r"../permuted_data.npy") #np.load(r'../Data Sets/Debug Data/permuted_data.npy')
proj_out_all = np.load(r"../proj_out_all.npy") #np.load(r'../Data Sets/Debug Data/proj_out_all.npy')
aux_diff_poisson = np.load(r"../aux_diff_poisson.npy") #np.load(r'../Data Sets/Debug Data/aux_diff_poisson.npy')

In [202]:
print(permuted_data.shape)
print(proj_out_all.shape)
print(aux_diff_poisson.shape)

(8, 4, 4)
(8, 4, 4)
(8, 4, 4)


In [209]:
print(permuted_data[:,0,0])
print(proj_out_all[:,0,0])
print(aux_diff_poisson[:,0,0])
# negative projection data...

[  0.69836503   0.839173    21.605843   216.13242    102.646805
   0.92443      0.6229484    0.5012255 ]
[-9.80411e-11 -9.80411e-11 -9.80411e-11 -9.80411e-11 -9.80411e-11
 -9.80411e-11 -9.80411e-11 -9.80411e-11]
[nan nan nan nan nan nan nan nan]
