In [177]:
from forward_backward_AD import *

import numpy as np
import torch
import time, timeit

import scipy.io

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [170]:
workspace = scipy.io.loadmat(r'../Data Sets/Debug Data/workspace_calc_grad.mat')

c:\Users\Bruker\anaconda3\envs\SAXSTT\lib\site-packages\scipy\io\matlab\mio.py:226: MatReadWarning: Duplicate variable name "None" in stream - replacing previous with new
Consider mio5.varmats_from_mat to split file into single variable files
  matfile_dict = MR.get_variables(variable_names)


In [3]:
print(workspace.keys())

dict_keys(['__header__', '__version__', '__globals__', 'opt_inputs', 'p', 's', 'projection', 'E', 'numOfCoeffs', 'skip_optimization', 'None', 'return_synth_proj', 'return_Ereg', 'find_coefficients', 'find_orientation', 'find_grad', 'phi_det', 'theta_det', 'l', 'm', 'nx', 'ny', 'nz', 'numOfsegments', 'numOfvoxels', 'mask3D', 'numOfpixels', 'numOfordersopt', 'theta_struct', 'phi_struct', 'a', 'ii', 'grad_a', 'grad_theta_struct', 'grad_phi_struct', 'zeros_struct', 'Ylm_coef', 'a_temp', 'a_temp1', 'a_temp2', 'ones_struct', 'unit_q_beamline', 'N', 'x', 'y', 'z', 'X', 'Y', 'Z', '__function_workspace__'])


In [171]:
theta_struct_it = workspace['theta_struct']
phi_struct_it = workspace['phi_struct']
a_temp_it =    workspace['a_temp']
ny = workspace['ny']
nx = workspace['nx']
nz = workspace['nz']
numOfsegments = workspace['numOfsegments']
current_projection = workspace['projection'][0,0]#[2]
p = workspace['p']
X = workspace['X']
Y = workspace['Y']
Z = workspace['Z']
numOfpixels = workspace['numOfpixels']
unit_q_beamline = workspace['unit_q_beamline']
Ylm_coef = workspace['Ylm_coef']
find_coefficients = workspace['find_coefficients']
find_orientation = workspace['find_orientation']
numOfCoeffs = workspace['numOfCoeffs']
numOfvoxels = workspace['numOfvoxels']



In [188]:
#print(current_projection[0,0][2].shape)
# Testing shit

print(type(numOfvoxels))

yo = int(np.squeeze(numOfvoxels))

print(yo)

print(type(yo))

new_tens = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], dtype=torch.float64).reshape(4,4)
print(new_tens)


A = torch.rand((3,3,64))
B = torch.rand((3,8))
#C = torch.matmul(A[0], B) # Have to figure out how this works. 

projection_data = torch.tensor(
        current_projection["data"])

print(projection_data.shape)

print(current_projection["data"].shape)
print(current_projection["Rot_exp"].shape)


<class 'numpy.ndarray'>
64
<class 'int'>
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]], dtype=torch.float64)
torch.Size([4, 4, 8])
(4, 4, 8)
(3, 3)


Done debugging. Error is at least correct. 

In [180]:
main(theta_struct_it, phi_struct_it, a_temp_it, ny, nx, nz, numOfsegments, current_projection, p, X, Y, Z, numOfpixels, unit_q_beamline, Ylm_coef, find_coefficients, find_orientation, numOfCoeffs, numOfvoxels)

(0.2076742798089981,
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.14486932, -0.19772309, -0.25057685, -0.30343061,
        -0.16993863, -0.22433007, -0.27872152, -0.33311297, -0.10750408,
        -0.10607129, -0.1046385 , -0.10320571,  0.        ,  0.        ,
         0.        ,  0.        , -0.22354727, -0.32561552, -0.42768378,
        -0.52975204, -0.2533951 , -0.35948618, -0.46557727, -0.57166835,
        -0.12877968, -0.12677393, -0.12476818, -0.12276242,  0.        ,
         0.        ,  0.        ,  0.        , -0.10882365, -0.16727035,
        -0.22571705, -0.28416376, -0.1184528 , -0.17900812, -0.23956344,
        -0.30011876, -0.04521856, -0.04348649, -0.04175441, -0.04002234,
         0.        ,  0.        ,  0.        ,  0.        ]),
 array([], dtype=float64),
 array([], dty

In [146]:
x = np.arange(64).reshape(4,4,4)
y = np.arange(64).reshape(4,4,4)

lower = np.argwhere( x>10)
upper = np.argwhere(x<20)

y = np.argwhere( (x>10) & (x<20) & (y>15) & (y<25) )
print(y)

# Next is out of bounds. Index 5 found when size is 4, index 3 is therefore max. 
print(x[y[:,0], y[:,1], y[:,2] ])

[[1 0 0]
 [1 0 1]
 [1 0 2]
 [1 0 3]]
[16 17 18 19]


In [168]:

# print(X)
# print('\n')
# print(Y)

Ax = np.floor(
    X - (-1.38545603) + 1
)  # Drop +1 due to 0-indexing. AI suggested, but believe I should copy cpp-code
Ay = np.floor(Y - (-0.19120833) + 1)

indices = np.argwhere( (Ax>0) & (Ax<4) & (Ay>0) & (Ay<4) )

print(Ax[indices[:,0], indices[:,1], indices[:,2] ])
print(Ay[indices[:,0], indices[:,1], indices[:,2] ])

[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.
 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [187]:
u1 = np.ones((3,3,3))
u2 = np.ones((3,3,3))

v = torch.tensor( u1 @ u2)
print(v)

tensor([[[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]], dtype=torch.float64)
