In [14]:
from forward_backward_AD import *

import numpy as np
import torch
import time, timeit

import scipy.io

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
workspace = scipy.io.loadmat(r'../Data Sets/Debug Data/workspace_calc_grad.mat')

In [7]:
print(workspace.keys())

dict_keys(['__header__', '__version__', '__globals__', 'opt_inputs', 'p', 's', 'projection', 'E', 'numOfCoeffs', 'skip_optimization', 'None', 'return_synth_proj', 'return_Ereg', 'find_coefficients', 'find_orientation', 'find_grad', 'phi_det', 'theta_det', 'l', 'm', 'nx', 'ny', 'nz', 'numOfsegments', 'numOfvoxels', 'mask3D', 'numOfpixels', 'numOfordersopt', 'theta_struct', 'phi_struct', 'a', 'ii', 'grad_a', 'grad_theta_struct', 'grad_phi_struct', 'zeros_struct', 'Ylm_coef', 'a_temp', 'a_temp1', 'a_temp2', 'ones_struct', 'unit_q_beamline', 'N', 'x', 'y', 'z', 'X', 'Y', 'Z', '__function_workspace__'])


In [16]:
theta_struct_it = workspace['theta_struct']
phi_struct_it = workspace['phi_struct']
a_temp_it =    workspace['a_temp']
ny = workspace['ny']
nx = workspace['nx']
nz = workspace['nz']
numOfsegments = workspace['numOfsegments']
current_projection = workspace['projection'][0,0]#[2]
p = workspace['p']
X = workspace['X']
Y = workspace['Y']
Z = workspace['Z']
numOfpixels = workspace['numOfpixels']
unit_q_beamline = workspace['unit_q_beamline']
Ylm_coef = workspace['Ylm_coef']
find_coefficients = workspace['find_coefficients']
find_orientation = workspace['find_orientation']
numOfCoeffs = workspace['numOfCoeffs']
numOfvoxels = workspace['numOfvoxels']



In [5]:
#print(current_projection[0,0][2].shape)
# Testing shit

print(type(numOfvoxels))

yo = int(np.squeeze(numOfvoxels))

print(yo)

print(type(yo))

new_tens = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], dtype=torch.float64).reshape(4,4)
print(new_tens)


A = torch.rand((3,3,64))
B = torch.rand((3,8))
#C = torch.matmul(A[0], B) # Have to figure out how this works. 

projection_data = torch.tensor(
        current_projection["data"])

print(projection_data.shape)

print(current_projection["data"].shape)
print(current_projection["Rot_exp"].shape)


<class 'numpy.ndarray'>
64
<class 'int'>
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]], dtype=torch.float64)
torch.Size([4, 4, 8])
(4, 4, 8)
(3, 3)


Done debugging. Error is at least correct. 

In [17]:
main(theta_struct_it, phi_struct_it, a_temp_it, ny, nx, nz, numOfsegments, current_projection, p, X, Y, Z, numOfpixels, unit_q_beamline, Ylm_coef, find_coefficients, find_orientation, numOfCoeffs, numOfvoxels)

DEBUG:root:Before a_temp_it shape: 64
DEBUG:root:After a_temp_it shape: torch.Size([64])
DEBUG:root:Rot_str shape: torch.Size([3, 3, 64])
DEBUG:root:unit_q_object shape: torch.Size([3, 8])
DEBUG:root:A shape: torch.Size([3, 3, 64])
DEBUG:root:B shape: torch.Size([3, 8])
DEBUG:root:cos_theta_sh_cut shape: torch.Size([8, 64])
DEBUG:root:Ylm_coef: tensor([0.2821], dtype=torch.float64)
DEBUG:root:block_cos_theta_powers shape: torch.Size([1, 8, 64])
DEBUG:root:A shape: torch.Size([1])
DEBUG:root:B shape: torch.Size([1, 8, 64])
DEBUG:root:A dims: 2
DEBUG:root:B dims: 3
DEBUG:root:Ylm shape: torch.Size([1, 8, 64])
DEBUG:root:a_temp shape: torch.Size([64])
DEBUG:root:A shape: torch.Size([64])
DEBUG:root:B shape: torch.Size([1, 8, 64])
DEBUG:root:sumlm_alm_Ylm shape: torch.Size([1, 8, 64])
DEBUG:root:data_synt_vol shape: torch.Size([4, 4, 4, 8])
DEBUG:root:Data type, shape: torch.float32, torch.Size([4, 4, 8])
DEBUG:root:xout shape: (4,)
DEBUG:root:yout shape: (4,)
DEBUG:root:
xout: [-1.3854560

proj_out_all: tensor([[[1.6223e-10, 1.6223e-10, 1.6223e-10, 1.6223e-10, 1.6223e-10,
          1.6223e-10, 1.6223e-10, 1.6223e-10],
         [6.5339e-10, 6.5339e-10, 6.5339e-10, 6.5339e-10, 6.5339e-10,
          6.5339e-10, 6.5339e-10, 6.5339e-10],
         [6.5339e-10, 6.5339e-10, 6.5339e-10, 6.5339e-10, 6.5339e-10,
          6.5339e-10, 6.5339e-10, 6.5339e-10],
         [4.6183e-10, 4.6183e-10, 4.6183e-10, 4.6183e-10, 4.6183e-10,
          4.6183e-10, 4.6183e-10, 4.6183e-10]],

        [[2.0058e-10, 2.0058e-10, 2.0058e-10, 2.0058e-10, 2.0058e-10,
          2.0058e-10, 2.0058e-10, 2.0058e-10],
         [8.0786e-10, 8.0786e-10, 8.0786e-10, 8.0786e-10, 8.0786e-10,
          8.0786e-10, 8.0786e-10, 8.0786e-10],
         [8.0786e-10, 8.0786e-10, 8.0786e-10, 8.0786e-10, 8.0786e-10,
          8.0786e-10, 8.0786e-10, 8.0786e-10],
         [5.7102e-10, 5.7102e-10, 5.7102e-10, 5.7102e-10, 5.7102e-10,
          5.7102e-10, 5.7102e-10, 5.7102e-10]],

        [[2.0058e-10, 2.0058e-10, 2.0058e-10, 

(0.20768234133720398,
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.11999981, -0.18959601, -0.2591922 , -0.32878839,
        -0.12267426, -0.19217514, -0.26167602, -0.33117689, -0.0370274 ,
        -0.03567798, -0.03432856, -0.03297915,  0.        ,  0.        ,
         0.        ,  0.        , -0.22132965, -0.36001161, -0.49869357,
        -0.63737552, -0.22229672, -0.36157039, -0.50084406, -0.64011773,
        -0.0512583 , -0.04936334, -0.04746837, -0.04557341,  0.        ,
         0.        ,  0.        ,  0.        , -0.13431723, -0.2159966 ,
        -0.29767597, -0.37935534, -0.13561856, -0.21731783, -0.29901709,
        -0.38071635, -0.03506898, -0.03374624, -0.0324235 , -0.03110076,
         0.        ,  0.        ,  0.        ,  0.        ]),
 array([], dtype=float64),
 array([], dt

In [146]:
x = np.arange(64).reshape(4,4,4)
y = np.arange(64).reshape(4,4,4)

lower = np.argwhere( x>10)
upper = np.argwhere(x<20)

y = np.argwhere( (x>10) & (x<20) & (y>15) & (y<25) )
print(y)

# Next is out of bounds. Index 5 found when size is 4, index 3 is therefore max. 
print(x[y[:,0], y[:,1], y[:,2] ])

[[1 0 0]
 [1 0 1]
 [1 0 2]
 [1 0 3]]
[16 17 18 19]


In [168]:

# print(X)
# print('\n')
# print(Y)

Ax = np.floor(
    X - (-1.38545603) + 1
)  # Drop +1 due to 0-indexing. AI suggested, but believe I should copy cpp-code
Ay = np.floor(Y - (-0.19120833) + 1)

indices = np.argwhere( (Ax>0) & (Ax<4) & (Ay>0) & (Ay<4) )

print(Ax[indices[:,0], indices[:,1], indices[:,2] ])
print(Ay[indices[:,0], indices[:,1], indices[:,2] ])

[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.
 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [187]:
u1 = np.ones((3,3,3))
u2 = np.ones((3,3,3))

v = torch.tensor( u1 @ u2)
print(v)

tensor([[[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]], dtype=torch.float64)


In [201]:
# Check out nan values

permuted_data = np.load(r"../permuted_data.npy") #np.load(r'../Data Sets/Debug Data/permuted_data.npy')
proj_out_all = np.load(r"../proj_out_all.npy") #np.load(r'../Data Sets/Debug Data/proj_out_all.npy')
aux_diff_poisson = np.load(r"../aux_diff_poisson.npy") #np.load(r'../Data Sets/Debug Data/aux_diff_poisson.npy')

In [202]:
print(permuted_data.shape)
print(proj_out_all.shape)
print(aux_diff_poisson.shape)

(8, 4, 4)
(8, 4, 4)
(8, 4, 4)


In [209]:
print(permuted_data[:,0,0])
print(proj_out_all[:,0,0])
print(aux_diff_poisson[:,0,0])
# negative projection data...

[  0.69836503   0.839173    21.605843   216.13242    102.646805
   0.92443      0.6229484    0.5012255 ]
[-9.80411e-11 -9.80411e-11 -9.80411e-11 -9.80411e-11 -9.80411e-11
 -9.80411e-11 -9.80411e-11 -9.80411e-11]
[nan nan nan nan nan nan nan nan]
