In [99]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
from plots import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [98]:
x = np.linspace(-1.69,1.69,100)
y = np.linspace(-1.69,1.69,100)

plot_3D_GD(GD_cost_func, x, y)

(<Figure size 800x600 with 1 Axes>, <Axes3DSubplot:>)

In [100]:
animate_3D_GD(GD_cost_func, x, y, (-1,1), 150, step=0.02)

tensor([-1.,  1.], dtype=torch.float64, requires_grad=True)
tensor([-0.9978,  1.0094], dtype=torch.float64, requires_grad=True)
tensor([-0.9956,  1.0187], dtype=torch.float64, requires_grad=True)
tensor([-0.9932,  1.0280], dtype=torch.float64, requires_grad=True)
tensor([-0.9907,  1.0373], dtype=torch.float64, requires_grad=True)
tensor([-0.9880,  1.0465], dtype=torch.float64, requires_grad=True)
tensor([-0.9853,  1.0556], dtype=torch.float64, requires_grad=True)
tensor([-0.9824,  1.0647], dtype=torch.float64, requires_grad=True)
tensor([-0.9795,  1.0737], dtype=torch.float64, requires_grad=True)
tensor([-0.9764,  1.0826], dtype=torch.float64, requires_grad=True)
tensor([-0.9732,  1.0915], dtype=torch.float64, requires_grad=True)
tensor([-0.9698,  1.1004], dtype=torch.float64, requires_grad=True)
tensor([-0.9664,  1.1091], dtype=torch.float64, requires_grad=True)
tensor([-0.9628,  1.1178], dtype=torch.float64, requires_grad=True)
tensor([-0.9591,  1.1264], dtype=torch.float64, requires

: 